### ISSUE TITLE
Алгоритм базы знаний на фреймах

### ISSUE THREAD

**Issue by sozmi** [sozmi/ExpertSystem#11]
Найти и написать в каком формате нужно хранить данные. 
Подумать какие структуры нужно будет реализовать.

**Comment by Minnou** [comment]
В самом простом варианте фреймы состоят из названия и свойств\слотов. Например, фрейм "машина" может иметь слоты:
```
цвет: красный
скорость: большая
цена: дорогая
```


Скорее всего, самый простой вариант хранения - база данных с двумя таблицами:
Таблица `frames` со столбцами `id` и `name`
Таблица `slots` со столбцами `id` `name` `value` и внешним ключом на фрейм из таблицы `frames`.

Структуры:
структура\класс `Frame` с полями `name` и `slots`
`slots` - словарь ключ - значение, ну понятно. ключ - цвет значение - красный
Естественно нужно реализовать парсинг базы данных для заполнения слотов фрейма по названию.
И наоборот создание фрейма в базе данных на основе объекта класса `Frame`

Можно так же усложнить всё, добавив иерархию фреймов. В таком случае необходимо ещё хранить "родителя" фрейма. Так например, у фрейма `рено логан` родителем будет фрейм `машина`. В таком случае необходимо добавить в базу данных и в структуру поле `parent`. Скорее всего нам это пригодится.
![Снимок](https://github.com/user-attachments/assets/c551d163-052f-40b7-90fe-f39489228c6b)

**Comment by sozmi** [comment]
Спасибо. Предлагаю не усложнять проект добавлением базы данных. Думаю, проще будет хранить данные в json.
