### ISSUE TITLE
Разработка базы знаний на фреймах

### ISSUE THREAD

**Issue by sozmi** [sozmi/ExpertSystem#15]
В библиотеке классов создать папку "frame_es".
Создать в этой папке диаграмму классов.
Вынести свойства в отдельный класс с полями id - int, name - string
Создать в этой папке классы со структурой, определенной в вопросе #11.

Поместить классы на диаграмму.

Примечание.
Все поля должны иметь публичные свойства.
Все публичные свойства и методы должны иметь заголовочный комментарий.

К вопросу прикрепить скриншот диаграммы классов

**Comment by Minnou** [comment]
Диаграмма классов:
![изображение](https://github.com/user-attachments/assets/ee9f0246-4a84-42ba-a2ee-c84f3ae50595)
