### ISSUE TITLE
Создание красивой стартовой страницы

### ISSUE THREAD

**Issue by sozmi** [sozmi/ExpertSystem#42]
Самое лучшее задание, полная свобода действий  :)
Проект WPF. Папка View/StartPage.xaml
Компоненты: https://github.com/HandyOrg/HandyControl

**Comment by LuiREN** [comment]
### 1. Изображение для главного окна
[ES.zip](https://github.com/user-attachments/files/17945957/ES.zip)

- переместить в WpfAppES\Icons\ES.ico

- в свойствах .ico проставить:

![image](https://github.com/user-attachments/assets/632acceb-2150-4b56-a3e7-8f85a7c267ea)
### 2.StartPage.xaml:
[StartPage.zip](https://github.com/user-attachments/files/17946064/StartPage.zip)

### 3.StartPage.xaml.cs:
[StartPage.xaml.zip](https://github.com/user-attachments/files/17946075/StartPage.xaml.zip)
