### ISSUE TITLE
Алгоритм логической базы знаний

### ISSUE THREAD

**Issue by sozmi** [sozmi/ExpertSystem#8]
Найти и написать в каком формате нужно хранить данные.
Подумать какие структуры нужно будет реализовать.

**Comment by RedRanger2020** [comment]
![image](https://github.com/user-attachments/assets/c76f711f-c560-4174-a0da-093b1778bcb9)

В логической базе знаний данные задаются предикатами. Имеем: объекты и их свойства. Для того, чтобы различать объекты и свойства вводим Q() - обозначает, что это объект и R() - это свойство. Как будто бы это можно убрать, чем упростить работу.

Далее, при помощи предикатов P(x,y) связываем объекты (x) и их св-ва (y). Так, P(x,y) означает, что у объекта x есть св-во y, а ~P(x,y) - эквивалентно !P(x,y) - что объекту x НЕ соответствует св-во y.

Далее через цепочку смотрим:
Например, у объекта x есть крылья, колёса, винт и он возит грузы. О, это самолёт!
Или: у объекта x нет крыльев и винтов, но он возит грузы и на колёсах. Так это же грузовик!

**Структуры:**
Класс "Объект" с полем name (То, что в таблице названо "Константы") и словарём, где ключ - название, значение - бинарное да/нет.

**Comment by sozmi** [comment]
Исходя из того, что свойства у объектов повторяются, необходимо выделить свойства в отдельный класс.
Итого:
Объект с полем name,  словарь[идентификатор свойства] = бинарное значение
Свойство с полями name, id - int
