### ISSUE TITLE
Алгоритм продукционной базы знаний

### ISSUE THREAD

**Issue by sozmi** [sozmi/ExpertSystem#9]
Найти и написать в каком формате нужно хранить данные.
Подумать какие структуры нужно будет реализовать.
Образец: https://github.com/jurahf/ES
Примечание, использование сериализации не желательно. Задолбаемся искать ошибки)

**Comment by LuiREN** [comment]
**1.Формат хранения данных:**

База знаний будет храниться в файле формата JSON. Структура файла будет включать три основных раздела:

> questions - массив вопросов, задаваемых пользователю
> rules - массив правил для определения результата
> results - массив возможных результатов и рекомендаций

Пример JSON файла базы знаний:
[knowledge-base-json.json](https://github.com/user-attachments/files/17367022/knowledge-base-json.json)

**2.Структуры данных:**

Будут реализованы следующие классы:

> Question - представляет вопрос, содержит поля Id, Text, Answers.
> Answer - представляет вариант ответа на вопрос, содержит поля Id, Text.
> Rule - представляет правило, содержит поля Id, Conditions, ResultId.
> Condition - представляет условие правила, содержит поля QuestionId, AnswerId.
> Result - представляет результат и рекомендации, содержит поля Id, Text, Recommendations.
> InferenceEngine - реализует механизм логического вывода, работает с базой знаний.

Взаимодействие классов будет организовано согласно следующей схеме:
![классы](https://github.com/user-attachments/assets/a5678e2e-72a9-427e-953f-ff27afbad9af)

**3.Процесс работы экспертной системы:**

> Загрузка базы знаний из JSON файла.
> Последовательный вывод вопросов пользователю и получение его ответов.
> Сопоставление ответов пользователя с условиями правил.
> Определение результата и рекомендаций на основе сработавшего правила.
> Вывод результата и рекомендаций пользователю.

**4.Методы работы с базой знаний:**

В классе InferenceEngine будут реализованы методы:

LoadKnowledgeBase(file) - для загрузки базы знаний из JSON файла.
SaveKnowledgeBase(file) - для сохранения базы знаний в JSON файл.

При реализации методов LoadKnowledgeBase и SaveKnowledgeBase будут использоваться встроенные средства работы с файлами и JSON в C#

**Comment by sozmi** [comment]
1) Интерфейс InferenceEngine дублирует интерфейс из вопроса #34 
2) Продукционная база знаний основывается на фактах, а здесь они не фигурируют, думаю, материал подобран неккоректно.

Рекомендую дополнить/изменить статью руководствуясь материалом
https://tproger.ru/articles/expert-systems
http://bibl.rusoil.net/base_docs/UGNTU/ATM/Murtazin.pdf
